
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef SILLYSLAVE_H
#define SILLYSLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 SillySlave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * SillySlave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data SillySlave_Data;
extern UNS8 LifeSignal;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 ADCDATA[4];		/* Mapped at index 0x2002, subindex 0x01 - 0x04 */

#endif // SILLYSLAVE_H
